export const realProjects = [
  {
    id: 'ai-healthcare',
    title: {
      en: 'AI Healthcare Platform',
      uk: 'AI Платформа для Медицини',
      pl: 'Platforma AI dla Opieki Zdrowotnej',
      de: 'KI-Gesundheitsplattform',
      es: 'Plataforma de Salud con IA',
    },
    description: {
      en: 'Medical diagnostics platform with AI-powered analysis, patient management system, and real-time telemedicine capabilities. Integrated with HL7 FHIR standards.',
      uk: 'Платформа медичної діагностики з AI-аналізом, системою управління пацієнтами та можливостями телемедицини в реальному часі.',
      pl: 'Platforma diagnostyki medycznej z analizą AI, systemem zarządzania pacjentami i możliwościami telemedycyny w czasie rzeczywistym.',
      de: 'Medizinische Diagnoseplattform mit KI-gestützter Analyse, Patientenverwaltungssystem und Echtzeit-Telemedizin.',
      es: 'Plataforma de diagnóstico médico con análisis de IA, sistema de gestión de pacientes y capacidades de telemedicina en tiempo real.',
    },
    tech: ['React', 'TypeScript', 'Node.js', 'PostgreSQL', 'Docker', 'AWS'],
    metrics: {
      en: ['5K+ patients', 'HIPAA compliant', 'Real-time diagnostics'],
      uk: ['5K+ пацієнтів', 'HIPAA сумісність', 'Діагностика в реальному часі'],
      pl: ['5K+ pacjentów', 'Zgodność z HIPAA', 'Diagnostyka w czasie rzeczywistym'],
      de: ['5K+ Patienten', 'HIPAA-konform', 'Echtzeit-Diagnostik'],
      es: ['5K+ pacientes', 'Compatible HIPAA', 'Diagnóstico en tiempo real'],
    },
    url: null,
  },
  {
    id: 'fintech-analytics',
    title: {
      en: 'FinTech Analytics Dashboard',
      uk: 'FinTech Аналітична Панель',
      pl: 'Panel Analityczny FinTech',
      de: 'FinTech-Analyse-Dashboard',
      es: 'Panel de Análisis FinTech',
    },
    description: {
      en: 'Real-time financial analytics platform processing millions of transactions daily. Custom reporting engine, fraud detection, and automated compliance monitoring.',
      uk: 'Платформа фінансової аналітики в реальному часі, яка обробляє мільйони транзакцій щодня. Кастомний звітний модуль, виявлення шахрайства.',
      pl: 'Platforma analityki finansowej w czasie rzeczywistym przetwarzająca miliony transakcji dziennie. Niestandardowy silnik raportowania, wykrywanie oszustw.',
      de: 'Echtzeit-Finanzanalyseplattform, die täglich Millionen von Transaktionen verarbeitet. Benutzerdefinierte Berichts-Engine, Betrugserkennung.',
      es: 'Plataforma de análisis financiero en tiempo real que procesa millones de transacciones diarias. Motor de informes personalizado, detección de fraude.',
    },
    tech: ['Next.js', 'Python', 'Redis', 'PostgreSQL', 'Kubernetes', 'GCP'],
    metrics: {
      en: ['2M+ transactions/day', '99.99% uptime', 'Sub-second queries'],
      uk: ['2М+ транзакцій/день', '99.99% uptime', 'Запити <1 сек'],
      pl: ['2M+ transakcji/dzień', '99.99% czas pracy', 'Zapytania <1s'],
      de: ['2M+ Transaktionen/Tag', '99.99% Verfügbarkeit', 'Abfragen <1s'],
      es: ['2M+ transacciones/día', '99.99% disponibilidad', 'Consultas <1s'],
    },
    url: null,
  },
  {
    id: 'ecommerce-platform',
    title: {
      en: 'Multi-Vendor E-Commerce Platform',
      uk: 'Мультивендорна E-Commerce Платформа',
      pl: 'Platforma E-Commerce Multi-Vendor',
      de: 'Multi-Vendor E-Commerce-Plattform',
      es: 'Plataforma E-Commerce Multi-Vendor',
    },
    description: {
      en: 'Scalable marketplace with vendor management, inventory sync, payment processing, and automated fulfillment. Built for 10K+ concurrent users.',
      uk: 'Масштабований маркетплейс з управлінням продавцями, синхронізацією інвентарю, обробкою платежів та автоматизованим виконанням замовлень.',
      pl: 'Skalowalny marketplace z zarządzaniem dostawcami, synchronizacją inwentarza, przetwarzaniem płatności i zautomatyzowaną realizacją.',
      de: 'Skalierbarer Marktplatz mit Lieferantenverwaltung, Bestandssynchronisierung, Zahlungsabwicklung und automatisierter Auftragsabwicklung.',
      es: 'Marketplace escalable con gestión de proveedores, sincronización de inventario, procesamiento de pagos y cumplimiento automatizado.',
    },
    tech: ['React', 'Node.js', 'MongoDB', 'Stripe', 'AWS', 'Docker'],
    metrics: {
      en: ['15K+ products', '500+ vendors', '50K+ orders/month'],
      uk: ['15K+ товарів', '500+ продавців', '50K+ замовлень/місяць'],
      pl: ['15K+ produktów', '500+ dostawców', '50K+ zamówień/miesiąc'],
      de: ['15K+ Produkte', '500+ Anbieter', '50K+ Bestellungen/Monat'],
      es: ['15K+ productos', '500+ proveedores', '50K+ pedidos/mes'],
    },
    url: null,
  },
  {
    id: 'devops-infrastructure',
    title: {
      en: 'Cloud Infrastructure Automation',
      uk: 'Автоматизація Хмарної Інфраструктури',
      pl: 'Automatyzacja Infrastruktury Chmurowej',
      de: 'Cloud-Infrastruktur-Automatisierung',
      es: 'Automatización de Infraestructura en la Nube',
    },
    description: {
      en: 'Complete DevOps transformation: CI/CD pipelines, infrastructure as code, auto-scaling, monitoring, and cost optimization reducing cloud costs by 40%.',
      uk: 'Повна DevOps трансформація: CI/CD pipelines, інфраструктура як код, автомасштабування, моніторинг та оптимізація витрат зі зниженням на 40%.',
      pl: 'Kompletna transformacja DevOps: potoki CI/CD, infrastruktura jako kod, autoskalowanie, monitorowanie i optymalizacja kosztów o 40%.',
      de: 'Vollständige DevOps-Transformation: CI/CD-Pipelines, Infrastructure as Code, Auto-Scaling, Monitoring und 40% Kostenoptimierung.',
      es: 'Transformación DevOps completa: pipelines CI/CD, infraestructura como código, auto-escalado, monitoreo y optimización de costos del 40%.',
    },
    tech: ['Terraform', 'Kubernetes', 'GitHub Actions', 'Prometheus', 'Grafana', 'AWS'],
    metrics: {
      en: ['Zero downtime', '40% cost reduction', '10x faster deployments'],
      uk: ['Zero downtime', '40% зниження витрат', '10x швидше deploy'],
      pl: ['Zero przestojów', '40% redukcja kosztów', '10x szybsze wdrożenia'],
      de: ['Null Ausfallzeit', '40% Kostenreduktion', '10x schnellere Deployments'],
      es: ['Cero tiempo de inactividad', '40% reducción de costos', '10x despliegues más rápidos'],
    },
    url: null,
  },
  {
    id: 'saas-platform',
    title: {
      en: 'SaaS Project Management Platform',
      uk: 'SaaS Платформа Управління Проєктами',
      pl: 'Platforma SaaS do Zarządzania Projektami',
      de: 'SaaS-Projektmanagement-Plattform',
      es: 'Plataforma SaaS de Gestión de Proyectos',
    },
    description: {
      en: 'Multi-tenant SaaS platform with real-time collaboration, task automation, reporting, integrations with 20+ tools, and enterprise SSO.',
      uk: 'Мультитенантна SaaS платформа з колаборацією в реальному часі, автоматизацією задач, звітністю, інтеграціями з 20+ інструментів.',
      pl: 'Wielodostępna platforma SaaS z współpracą w czasie rzeczywistym, automatyzacją zadań, raportowaniem, integracjami z 20+ narzędziami.',
      de: 'Mandantenfähige SaaS-Plattform mit Echtzeit-Zusammenarbeit, Aufgabenautomatisierung, Reporting, Integration mit 20+ Tools.',
      es: 'Plataforma SaaS multi-tenant con colaboración en tiempo real, automatización de tareas, informes, integraciones con 20+ herramientas.',
    },
    tech: ['Next.js', 'TypeScript', 'PostgreSQL', 'Redis', 'WebSockets', 'Docker'],
    metrics: {
      en: ['200+ companies', 'Real-time sync', '20+ integrations'],
      uk: ['200+ компаній', 'Синхронізація в реальному часі', '20+ інтеграцій'],
      pl: ['200+ firm', 'Synchronizacja w czasie rzeczywistym', '20+ integracji'],
      de: ['200+ Unternehmen', 'Echtzeit-Synchronisation', '20+ Integrationen'],
      es: ['200+ empresas', 'Sincronización en tiempo real', '20+ integraciones'],
    },
    url: null,
  },
];
